# escape=`

FROM mcr.microsoft.com/windows/servercore:ltsc2025 as roots
COPY docker/windows/ C:/roots-src/
RUN powershell -NoProfile -ExecutionPolicy Bypass -File C:\roots-src\export-roots.ps1

FROM plugins/base:windows-ltsc2025-amd64@sha256:9b0c50ee6daca9a5eadef008c0beacf9e7e6f2209eea3260ca687468fb7b3b21
USER ContainerAdministrator
SHELL ["cmd", "/S", "/C"]
COPY --from=roots /roots/ /roots/
RUN for %f in (C:\roots\*.reg) do @(reg import "%f" || exit 1)
USER ContainerUser

ENV GODEBUG=netdns=go

ADD release/windows/amd64/drone-cache.exe C:/drone-cache.exe
ENTRYPOINT [ "C:\\drone-cache.exe" ]
